import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
const { PrismaClient } = require('@prisma/client')


export async function getServerSideProps(){
  try{
    const prisma = new PrismaClient()
    let arr =[]

   await  main()
    .then((e)=>    
    {      
      let fn= new Promise((resolve, rej)=>{    
      arr = e
      resolve()
    })

    fn.catch(e=>console.log(e))

    })
    .then(async () => {
      await prisma.$disconnect()
    })
    
    .catch(async (e) => {
      console.error(e)
      await prisma.$disconnect()
      process.exit(1)
    })

    async function main() { 
      let posts2 = await prisma?.usernames?.findMany({
        select:{
          name: true
        }
      })
      return posts2           
    }
   
    const posts =await JSON.stringify(arr)

    
    return{
      props:{posts}
    }
  }catch(e){
    return{
      props:{posts:[]}
    }
  }
 
}
export default function Home(props) {

  let arr =[]
  if(props?.posts !== undefined|| props?.posts !== null){
    arr = JSON.parse(props?.posts)    
  }  

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1>Mysql and Prisma</h1>

        <h1>List of my users</h1>

        <div>
          <Link href='/createUser' className={styles.linkColor}>Create a new User or a Post</Link>
        </div>

          <h1>Names:</h1>
          <ul>
            {arr?.map((e,i)=><li key={i}>{e?.name}</li>)}
          </ul>       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
